sudo: required
dist: trusty
env:
  global:
  # DOCKER_USER
  - secure: "oLU/a0zN09snAYcWZJdMewdJuLJNs1MAZm6E+dCXjdfrunQOptMMhpI8IAIl0/miYy2vdvk8OVChTTKyt3JPqQo/lQq/Xm3KyuJ031Ca0szlK7djKAauOV7d5NpPdJ7h8AOWWaYTmmGqqrX8AAGZH2oyaxcSlTsthGXJu+GbiHs90bRKoEu1kjUvOm57/Q9bMJxJ1deIzhKIpzjQgdc0aI+eMH0gNOLbUUVbi7a5BROF9C632HTQhj4voKymqsBIEAwpHgjEKkuQwZ4PwC9X5/gBUJyMKHU41q6CGoBhHrFsUQr5f7RKsH8vpRtoe93VdI9kWjvDHVqX0JzcynoAvqBGKTcooyfsODh/C7XKIbpuZfBPnbj5mRjD8L1lMCKblk75OBo3lgp505VoKACAgTa3S9D2CssflOUlFKdBSkvMjlyqzEl1o6F6KJeVmLPHv7UtEQBcpIFmFNOm84LOFn5BVxCWnOcKKlAEIUn8+aPgh1KU3AnfPryC6Zze8yXAwT+31cBvO7s4jN5O1CDRA61AANLOdgoRgMtYIq+qGGZ5M2hgGAmgONqZwDvdWhciJIyrzrC4c84DHy1B+Vj8aLaXlEc3AVSkzqoMMuUP0uKM7Ox8y1XPhU6hUVotYorTds7/s4dR0IP6sTpEQLn8yWVzDk/SEpWCUR6nSrGVHzE="
  # DOCKER_PASS
  - secure: "nGRT1tmF0ZFM8QVB4PzvjIrPuJRH2DdYZSOebHJApFTEYXMRx3RkCDsh6BquXum9x+Lk33A0S2nLNeHfb9NlsIi2WyWAkWIHKUbdbPIi4urj89IcXtJPNtTOP0+/f6BK/WmFTo4kOkZ7SMOoXzTQ0gVKgpJbnne9qatdAYJWjsXRnySlT1eVeMF8yfPEk2ul/jTwHnvZmRsX4sh1kqPVe93JrA5bnI/8c8M4kbLPWbpRg6r54kB9Zayukb+geVlBEdsBqeZaf948nOj8sBI+oY8tOMizqPU5zr1TVT8FwxpJPvbehVMcLPL5pqzXot9RAtLXhBAcu6yZGjR7HTQh83CrFVtKsARiKzQZ2tiAv9Go5kvexMEhoextuwLKn9vHGNYZKR9dpIowRiwZQFyTsGDB7+FXQtOCUsocYSXmgenQym6kP8iEhsokKaoKb3WEKMgH6XZvytzq9t/FIe6aevPxY8io1HeZ6S0TrmoVnV4dJ/PqEmZ18+2DQTdPhK4vF7LJ6DLLvS/bi7+Vu9qWU0r4EcMv9PREC2Hv1w6+GZkGUyTSjm5gODQ9DxQGaJkL3YJU6tFremmKWwvq8AJP5FY897nF0n2ZPeCptpF5c1SRoVJuAlWnY+e4CDn3D9l2UQtshKOamXuVgt4pbYlw9/YSG2Zc713nh9ROkJ+1UFU="
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_59c5939bd866_key -iv $encrypted_59c5939bd866_iv -in docker-creds.tar.enc -out docker-creds.tar -d

stages:
- name: build
- name: deploy
jobs:
  include:
  - stage: build
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --pull --rm -t threethink/minio:${TRAVIS_COMMIT} .
    - docker push threethink/minio:${TRAVIS_COMMIT}
    if: branch = master
  - stage: deploy
    env:
      # DOCKER_HOST
    - secure: "wSwxOpMsYbLkhGoZaPYN85G0NXrNRR6ob4fTrmw1BOQzoL/pNPCxw+m4qw5s8nUCRBEamObNunKht9HZrF7Ia0Dop+FRahAaD1VW7rHijExNqewG047nbKYTfBYf5JJ/ylXMrkDKNEIFEihmVh4CczCBmrWT50h7UfM2rO3DGzJNnqvfo3Lry1a7SOuElmOqlymRxuIvfXieDacoXW9GdBhPC5xwlNR0cDI7COmoVPHnhHD/KxuzWumfM4CmXIhwfOVlEaDfb+U6atv6oJehuJpbqJ/33GMt6z16FgHncAZE7SDzHQA/QgoNJriSE9uOT3SO7B+LhacuZKMXDvil7KT033QoogMwyYGDwIk/m2dUbJg0VpqzP++YsM8QaMbMak1xfnJN5aQ6liQGphhJtW7GQ3/1aAzxEB0zZVufnKnr3gjAR2tECzbEcj0veLR803GFccZBaC2JK7EV7F9zF60lyQ5ujOqvSqEMHbctLnaibwjJqCMZ3bZ15mG5tqml4vJ4VyFgDkUh8hVwIv4PT3pOxxY/bRFEiKtJKHoj6x0WCbJ1QwCguzcdKwCKO2bx6+DSoMxg2eRAKSvr3+XJQKz5O2dHrjTMOKmXoTf+VlydWSi9TFgB2u+xw/ybmBFyJ0Tl2sTfQWMlyKpZgbKISx0b/QQ9t2fJHP3BkuDsdto="
    - DOCKER_CERT_PATH="./docker-creds/docker-remote-secrets/"
    - DOCKER_TLS_VERIFY="True"
    # MINIO ACCESS KEY
    - secure: "GTTHzuKwYonKN1qb8c2WdIjUI8AVwlmM0HPLqbFd/7ZFcvVGw5koCa6/sqvaCveEV6Rycw0DcOT3sc0Cfsy4xAMjaLdDB80oL+r20CuN6uAAvpFLaUbsQ+hN083ISg9tzY8j3BPiFwGUivn542A8I0wQwScxT6+cXWi2MIxCz7waww82ARXgDwAJONbUZb9SDpkTAHQ5zsgk281vj2UVlOxpxBfMNv4g9TE+tk6RlqXzCsqDvJxJ4D8Szo1anpOf8maJj1KOTuPpKLQYo3uZYSzcDhEGnZUAx13IO+21Yqf4PVS+s+/B/lxcul0KzrdPhTN/mkJD2BT7IjN/ZTcqE3zEVbMMuFm8FpExnbt7R7dJtK2xmRvQtSlifAK2K2GVhEAo1F2A4F82YJaYUkRfXUg5iz3SNqifU6ORE7s5jjhwumLIxkalY5Ci72ojOLTlV6S5FW7mvAKX9WXDje+KMnwP5SnHzYpLyFL5ijzIkcIJjCqwc6BRcYJUKXj/74luN06S1xk0QfDX6jwa3XxhDUwgS6c0sRqGw/uxcxaEZ9N67xCSjYcqrlJaW00XQqHrLnnBhAPGesuB3CLWpPolXyPpCWfqP0x2KqTTUlaF7X2kNwESJdEGM3J8bVlmi2vwLxc73pX5ukhRxpUdpJZxWpvLV9DqlbVTI2nSYOAmW18="
    # MINIO SECRET KEY
    - secure: "r/wLHEUH1I7PG6E+tfnwyOxwPqro6tyH25su2020VvsnWFmjXw22MGVdTZFyp7cJrBPFf5DNrNGbtLvqnEwJvE4A+ytpeb2PufrSNmvLtZp4up41y1lmDZHHkHFeQVn3YgHzr6lghfUcUJWXpVxevL3fKR7k54Z1Vo0NtqCWvT1Np8Fuae2yeAv/ANP4p76ZUDdjjo9NqGZkK0olUqVE+V21Ok8Wk7OQWaDtv8tZgrZJJ32A05lXWYo6LDqG64+G2ko0D9roaG7VVfgmSKI/aiLOIyv5XGC2cldLgbtKpHg79PBOTUTUHj5dCZWuZ7zWr4oB2mZIhHylgwSu1mnvnY+vY5chOvoZtk6j768hI+2njg8tme4U7LJcQ+NgkE5V1S66IiE3wc+PKOpY34AUdJZ3IAuiJJQPsCVchKnpDYvMFErenb+nvHuLIb3rJlM3L/VgYi8f/ROPsi1oN/uL0Wp9omozH3u/XLOoquRgpgeUuKXIzoHpVAG2xOlVyC07l2WLj0cxfPWTmV7k5FZ+uaGdj5rfHeUNUsLycELo3M3/lIgVzo6wejcx2eAFzMBMARhyaouIkgoS/DAB3Lfwp/C/CAHu1zDXN96l6KieL9ZZ9X3I431p4n2MUCayS07Mb8MKrhkW5K00ChBCMOOowKviJt6OQpNiDahjrkNXVe4="
    script:
      - tar xvf docker-creds.tar # extracts the folder: docker-creds/docker-remote-secrets
      - docker-compose up -d
    if: branch = master
