version: '2.3'
services:
  minio:
    build: .
    image: minio/minio:RELEASE.2019-08-29T00-25-01Z
    scale: 1
    volumes:
      - /home/docker/data/dog-turds/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: ["server", "/data"]
    labels:
      - "traefik.enable=true"
      - "traefik.backend=minio"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:s3.threethink.io"
      - "traefik.docker.network=loadbalancer"
    ports:
      - "9000"
    cpu_count: 1
    mem_reservation: 512m
    mem_limit: 1500000000
    restart: always 
    networks:
    - dogturds
    - loadbalancer
networks:
  dogturds:
    external: true
  loadbalancer:
    external: true